# This Benthos config file creates a pipeline which:
#  - Listens on a NATS topic
#  - Sends the message to the Ollama API
#  - Returns the LLM response to another NATS topic
input:
  nats:
    urls:
      - nats://localhost:4222
    subject: messages.*.prompt
buffer:
  none: {}
pipeline:
  threads: -1
  processors:
    - branch:
        # Map the NATS message into the Ollama API request body format
        request_map: |
          root.stream = false
          root.model = "dolphin-mixtral"
          root.prompt = this.message
        processors:
          # Call the Ollama API
          - http:
              url: http://localhost:11434/api/generate
              verb: POST
              headers: {}
              rate_limit: ""
              timeout: 60s
              parallel: false
        # Map the Ollama API response into the NATS message format
        result_map: |
          root.message = this.response
output:
  broker:
    pattern: fan_out
    outputs:
      - stdout: {}
      - nats:
          urls:
            - nats://localhost:4222
          subject: ${!meta("nats_subject").replace_all("prompt", "response")}
